---
- name: Install packages for proxmox
  hosts: vmhosts
  become: yes
  tasks:
  - name: remove enterprise repo
    ansible.builtin.apt_repository:
      repo: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
      state: absent
      filename: pve-enterprise
  - name: create linux bridge for primary NIC
    ansible.builtin.copy:
      dest: /etc/network/interfaces/80-bridge-vmbr0
      marker: "## {mark} ANSIBLE MANAGED BLOCK"
      content: |
        auto vmbr0
        iface vmbr0 inet dhcp
                bridge-ports "{{ primary_nic }}"
        #        address 192.168.10.2/24
        #        gateway 192.168.10.1
                bridge-stp off
                bridge-fd 0
                bridge-vlan-aware yes
                bridge-vids 2-4094